name: hydrography
channels:
  - conda-forge
  - nodefaults # Speeds solving env, by limiting the number of options

dependencies:
  - python=3.11  # geoarrow not supported for 3.12 as of May 17, 2024

  # Geospatial libs for vector data
  - scipy
  - geopandas >=0.14.1  # supports GeoParquet 1.0.0
  - geoarrow-pyarrow  # high-performance geoarrow dtype for geometry, integrated with lonboard
  - gdal >=3.8.5  # Note: 3.9 officially supports geoarrow, but pyogrio not quite the as of May 17, 2024
  - pyogrio # Vectorized vector I/O using GDAL/OGR, speeds up GeoPandas!
        # PostGIS supported. See https://pyogrio.readthedocs.io/en/latest/supported_formats.html 
        # and full list of drivers: https://gdal.org/drivers/vector/index.html
  - geojson
  - openpyxl # read/write Excel 2010+ files (.xlsx & .xlsm)
  # For MacOS
  # - qgis # FoDesktop GIS within the same env and dependancies
  - libgdal-arrow-parquet # required for GeoParquet in QGIS on Mac
      # https://medium.com/radiant-earth-insights/the-geoparquet-ecosystem-at-1-0-0-96dee8ce9201
      # https://github.com/qgis/QGIS-Mac-Packager/issues/156

  # Remote Access
  - fsspec
  - s3fs  # Access to Amazon S3 filesystem

  # Hydro Data Tools
  - networkx  # For building graphs for watershed network analysis
  - pynhd  # HyRiver: provides access to NHD+ V2 data through NLDI and WaterData web services
  - pygeohydro # HyRiver: for accessing hydrology data through web services, 
        # including WBD for HUC bounaries

  # Database connections for exporting to PostGIS, which we may be covered by pyogrio
  # - psycopg2  
  # - sqlalchemy

  # Visualization
  - geoviews
  - datashader
  - panel >=0.14 # Major update for dashboarding
  - selenium # for HoloViz/bokeh.io image export functions
  - lonboard  # fast geospatial vector visualization, built on geoarrow
  # - contextily  # retrieve tile maps from the internet. Installs RasterIO.
  - cmasher # Adds function to subset colormaps, including from HoloViz's colorcet

  # Interactivity via Jupyter Notebooks
  - jupyterlab
  - nodejs  # required for many extensions
  - ipympl  # jupyter-matplotlib, https://github.com/matplotlib/ipympl
  - ipywidgets  # Required for HoloViz interactivity

  # Dev tools: Language Server Protocol (LSP) (Optional), for...
    # code navigation + hover suggestions + linters + autocompletion + rename
  - python-lsp-server >=1.6 # LSP extension for Python (pylsp), including:
    # Rope for Completions and renaming
    # Pyflakes linter to detect various errors
    # McCabe linter for complexity checking
    # pycodestyle linter for style checking
    # pydocstyle linter for docstring style checking (disabled by default)
    # autopep8 for code formatting
    # YAPF for code formatting (preferred over autopep8)
    # flake8 for error checking (disabled by default)
    # pylint for code linting (disabled by default)
  - pylsp-mypy  # MyPy type checking for Python >=3.7.
  - jupyterlab-lsp # Provides both server extension and lab extension

  # package management
  - conda
  - conda-build
  - conda-libmamba-solver

  # PIP install requirements only if it is not  possible with conda
  # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#using-pip-in-an-environment
  - pip
  - pip:
